/**
 * Dependency Injection Tokens
 * Centralized tokens for service registration
 */
export const TOKENS = {
  // Storage
  STORAGE: 'STORAGE',

  // Repositories
  COMPUTER_REPOSITORY: 'COMPUTER_REPOSITORY',
  STATS_REPOSITORY: 'STATS_REPOSITORY',
  TASK_REPOSITORY: 'TASK_REPOSITORY',

  // External Services
  WSUS_CLIENT: 'WSUS_CLIENT',
  SQL_CLIENT: 'SQL_CLIENT',
  POWERSHELL_EXECUTOR: 'POWERSHELL_EXECUTOR',

  // Application Services
  LOGGER: 'LOGGER',
  EVENT_BUS: 'EVENT_BUS',
  JOB_MANAGER: 'JOB_MANAGER',

  // Use Cases
  REFRESH_TELEMETRY_USE_CASE: 'REFRESH_TELEMETRY_USE_CASE',
  BULK_SYNC_COMPUTERS_USE_CASE: 'BULK_SYNC_COMPUTERS_USE_CASE',
  PERFORM_CLEANUP_USE_CASE: 'PERFORM_CLEANUP_USE_CASE',
  REINDEX_DATABASE_USE_CASE: 'REINDEX_DATABASE_USE_CASE',
  PROCESS_TERMINAL_COMMAND_USE_CASE: 'PROCESS_TERMINAL_COMMAND_USE_CASE',
  ADD_SCHEDULED_TASK_USE_CASE: 'ADD_SCHEDULED_TASK_USE_CASE',
  GET_SCHEDULED_TASKS_USE_CASE: 'GET_SCHEDULED_TASKS_USE_CASE',
  
  // Command Handler
  COMMAND_HANDLER: 'COMMAND_HANDLER',
} as const;
